### ISSUE TITLE
Create alpha tag once listed deps are merged and successful

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#108]
Once the below PRs are merged, we should create an alpha tag for the project and increment the version in the package.json/pom.xml. 

Depends on #98, #100, #101, #106

**Comment by chrisguindon** [comment]
I will create a tag now. We haven't decided what we will do with #100 yet.

**Comment by chrisguindon** [comment]
Done: https://github.com/EclipseFdn/react-eclipsefdn-members/releases/tag/v1.0-alpha
