### ISSUE TITLE
Generate kubernetes container definition

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#11]
In order to host this container within our cluster, a Kubernetes container definition/configuration file will be needed. This cluster should run the compiled Quarkus application ideally in the JVM run mode to save some memory and overhead. While native is ideal, it may present a challenge to fully implement in a way that is compatible with native run mode images.

**Comment by chrisguindon** [comment]
@autumnfound Let's add this at the top of our priority list. 

we will need to have this application hosted on our Custer for the next testing stage since we can deploy our REST API on Netlify.
