### ISSUE TITLE
[Proposal] JSLint or ESLint

### ISSUE THREAD

**Issue by linkfang** [EclipseFdn/react-eclipsefdn-members#110]
They have similar goals/functions, but it seems that ESLint is much more widely used.

Here are the repo info of them,
[JSLint](https://github.com/jslint-org/jslint): 
![image](https://user-images.githubusercontent.com/43075439/121949663-b8ee2c00-cd26-11eb-97ae-14637814c831.png)
(couldn't find "used by" data for JSLint)

[ESLint](https://github.com/eslint/eslint): 
![image](https://user-images.githubusercontent.com/43075439/121949710-c73c4800-cd26-11eb-94a1-ecbd62739f4a.png)
![image](https://user-images.githubusercontent.com/43075439/121949736-d02d1980-cd26-11eb-81a9-67e9655c7ee9.png)

And ESLint has a more comprehensive and detailed doc. 
[Doc ](https://eslint.org/)for ESLint, [doc ](https://www.jslint.com/)for JSLint. 

Here is the statement from ESLint,
In many ways, it is similar to JSLint and JSHint with a few exceptions:
- ESLint uses Espree for JavaScript parsing.
- ESLint uses an AST to evaluate patterns in code.
- ESLint is completely pluggable, every single rule is a plugin and you can add more at runtime.

So, in conclustion, I personally think ESLint is a better choice, because:
1.  ESLint is much more widely used.
2.  ESLint has a more comprehensive and detailed doc.
3.  ESLint claims to be more flexable.

**Comment by autumnfound** [comment]
We were already planning to use ESLint, weren't we? I had to poke around, but like said in an earlier meeting, we've used it in the past and have found a decent config set for standard JS rules. We may need to play around to get them tuned for React, but I imagine it wouldn't be a huge stretch https://github.com/EclipseFdn/jquery-eclipsefdn-api

**Comment by linkfang** [comment]
> We were already planning to use ESLint, weren't we? I had to poke around, but like said in an earlier meeting, we've used it in the past and have found a decent config set for standard JS rules. We may need to play around to get them tuned for React, but I imagine it wouldn't be a huge stretch https://github.com/EclipseFdn/jquery-eclipsefdn-api

Are we? I remembered Chris asked me to create a proposal issue for which one to use😅.

But if we already decided on this one, then good!

**Comment by autumnfound** [comment]
Also see https://github.com/EclipseFdn/eclipsefdn-github-sync/blob/master/package.json for a more recent usage of eslint in our projects

**Comment by autumnfound** [comment]
It might be that he wanted to check which is better for React? But yeah, we've used this before and I swear I've brought it up in our meetings a few times...oh well. At least you came to the same conclusion I did when I updated a few things in the past year or so, makes life easier ;)

**Comment by chrisguindon** [comment]
ESLint it is!
