### ISSUE TITLE
Add UCSB as Member on the website

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/react-eclipsefdn-members#111]
Hello, 
Please add UCSB as a Member on the OpenHW Group Website. 
Thanks,
Zahra
![UC-Santa-Barbara-Wordmark-Navy@1x (1)](https://user-images.githubusercontent.com/50374570/122061735-c9e97c80-cdbc-11eb-89b7-aaf5bf526c32.png)

**Comment by autumnfound** [comment]
I think you meant to post this somewhere else ;) [github.com/OpenHWGroup/openhwgroup.org](https://github.com/OpenHWGroup/openhwgroup.org)

**Comment by ZahraFazli** [comment]
Ah! my bad! I will close this issue. 
Thanks for pointing it out.
