### ISSUE TITLE
How should users find the Membership portal?

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#116]
It was decided that we should use https://membership.eclipse.org for the Membership Enrolment. This means that users will need to know the of https://membership.eclipse.org/portal  to access the portal.

I am thinking that we need to allow users to access the portal if they land on https://membership.eclipse.org.

Perhaps this is the 3rd option on the screen where we ask users to:

1) Create a new form
2) Edit an existing form
3) Continue to the membership portal

Let use this bug to discuss and decide how we expect users to log in to the membership portal.

**Comment by shanda-eclipse** [comment]
I think the member portal will be accessed on a more frequent basis than the enrollment form, as you would only fill out the enrollment form when joining and if our portal is as awesome as planned, members would be visiting that regularly. So I would recommend switching it so the enrollment for is something like https://membership.eclipse.org/application and the portal was  https://membership.eclipse.org.

**Comment by chrisguindon** [comment]
@shanda-eclipse That makes sense to me. 

However, we plan on launching the portal at the end of the year. What would you recommend we do in the meanwhile?

**Comment by chrisguindon** [comment]
How about this:

- /application
- /portal

and when we make this live, we setup a temporary redirect on / to /application.

At the end of the year, once we go live with this portal. we update the temporary redirect from /application to /portal.

**Comment by shanda-eclipse** [comment]
+1. Perfect solution!

**Comment by chrisguindon** [comment]
I created https://github.com/EclipseFdn/react-eclipsefdn-members/issues/140 in order to update the routes for the current application form and setup the redirect as we discussed.

We've already reserved /portal for the portal:
https://membership-staging.eclipse.org/portal

It's a very beautiful page :)

My understanding that any user that will try to reach /portal will be redirected to our login form if they are not logged in. We won't create a signing page as we did with the /application form.

Is that correct @shanda-eclipse ?

**Comment by shanda-eclipse** [comment]
> My understanding that any user that will try to reach /portal will be redirected to our login form if they are not logged in. We won't create a signing page as we did with the /application form.
> 
> Is that correct @shanda-eclipse ?

Ya, I think that makes sense. If they are already logged in, they would be taken right to the dashboard page.

**Comment by chrisguindon** [comment]
This is now in place. Closing this issue!
