### ISSUE TITLE
What content or entity we should make Searchable? 

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#119]
The mockup is including a search in the toolbar:
https://xd.adobe.com/view/57567fb8-f8dd-4e7e-8be8-ffbb26313a5a-0205/screen/0720f376-a05f-433f-93f4-76be127a78ee/

![Screenshot 2021-06-18 090816](https://user-images.githubusercontent.com/893942/122565669-bd5f6100-d014-11eb-9b48-d0962ba9f1fb.png)

@shanda-eclipse What is the purpose of this search? What do think our users need to be able to search?

**Comment by shanda-eclipse** [comment]
@meKokabi Let's remove the search functionality from the mock-up. I don't think it's needed.

**Comment by meKokabi** [comment]
The mockup has been updated: https://xd.adobe.com/view/57567fb8-f8dd-4e7e-8be8-ffbb26313a5a-0205/

**Comment by chrisguindon** [comment]
Thanks, @shanda-eclipse and @meKokabi
