### ISSUE TITLE
Create web form for membership enrollment

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#12]
In order to encapsulate and secure the UI fully, one of the most straightforward ways is to couple the UI and server more tightly. To this end, the UI layer should match the mockups as defined in #4 and be able to be compiled at build time to embed within the runtime package. 

The technology chosen for developing this form is React.js using some commonly available libraries to help bootstrap our development where possible. This form should be compatible with our currently supported browsers (IE11, FF, Chrome, Safari, Opera, etc.) to ensure the best and consistent experience for our users. 

When developing this, we should make sure that theming is somewhat easy to configure, as well as well documented on updates to better enable community updates when needed.

**Comment by flora8984461** [comment]
Let me copy my Rough todo here for reference:
- [ ] Log in (Store user Id)
- [ ] After login, display all forms the user has, allow him to create a new or continue with existing forms (Store selected form Id)
- [ ] Company Information
- [ ] Membership Level
- [ ] Working Group
- [ ] Signing Auth
- [ ] Review
- [ ] Style the Steppers
- [ ] What to do with the login Data? - After login, if there is some existing data, then...

**Comment by chrisguindon** [comment]
@autumnfound is this a dup of https://github.com/EclipseFdn/react-eclipsefdn-members/issues/17?

**Comment by chrisguindon** [comment]
I am going to close this but we can re-open if I am missing something here.
