### ISSUE TITLE
Discuss quick links in the toolbar

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#120]
We currently have 3 quick links icons in the toolbar:

![Screenshot 2021-06-18 091640](https://user-images.githubusercontent.com/893942/122566753-e6342600-d015-11eb-91fe-7071e2c3be65.png)

@shanda-eclipse Here's what I am thinking is the intent here:

1. Link to a help page. 
2. Link to our Hubspot chat
3. Notifications 

1 and 2 would be simple as they would link to a page or an external service.

For #3, we would need to define what counts as a notification. What did you have in mind for that?

**Comment by shanda-eclipse** [comment]
I think we can remove all 3 icons from the mock-up. We have already set-up hubspot chat support for the portal, which doesn't require those links. @chrisguindon if you agree, @meKokabi can remove these icons from the mock-up.

**Comment by chrisguindon** [comment]
+1 I think we are covered if the chatbox is available. 

The alternative could be to create a page with a Hubspot form that would allow members to reach out to the membership team if they have a question or an issue.

**Comment by chrisguindon** [comment]
@meKokabi I did see that you removed the search box but those icons are still there! Can you please let me know once they are gone?

**Comment by meKokabi** [comment]
@Christopher Guindon ***@***.***> Hi Chris, just
removed the icons as well!
https://xd.adobe.com/view/57567fb8-f8dd-4e7e-8be8-ffbb26313a5a-0205/

**Comment by chrisguindon** [comment]
Thanks @meKokabi
