### ISSUE TITLE
Create staging data tooling to generate random data 

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#13]
In the past, we have made use of old copies of production data for staging instances of databases to make data more coherent and reduce effort involved with the data. While our staging server is secured with the same protections as production, this increases risk with our data as we have additional data to maintain and protect. For the data produced and maintained by this service, staging instances should dump all data on start and generate random data to further protect our data.

**Comment by chrisguindon** [comment]
This is a great idea! 

Question: Do we really want this to be random? 

If we define proper fake data so that we can easily reproduce know issues?

**Comment by chrisguindon** [comment]
This is done!
