### ISSUE TITLE
Implement our Welcome User component in Toolbar with ability to logout

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#132]
On every page of our sites, our users expect our "Welcome Component" in our toolbar. This component is different based on the login state of the user. 

We currently display the same information regardless of the state and the logout link does not work. The m,anaged cookie is also broken.

Logged in users:

![Screenshot 2021-06-22 092854](https://user-images.githubusercontent.com/893942/122933070-4a1f5d00-d33c-11eb-8971-e44fa184cc25.png)

Not logged in:

![Screenshot 2021-06-22 092949](https://user-images.githubusercontent.com/893942/122933204-6a4f1c00-d33c-11eb-8be3-9bc92ef30d12.png)

For this app, we should link the login link to: api/login, and the logout link is a POST to /api/logout.

**Comment by linkfang** [comment]
Done!
