### ISSUE TITLE
Update TO VAT Registration field

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#133]
We would like to make the following changes to the **VAT Registration** field under #company-info.

![Screenshot 2021-06-22 101202](https://user-images.githubusercontent.com/893942/122940248-4ee70f80-d342-11eb-8e93-6e5f29160b92.png)

## VAT Registration

Is your organization registered for VAT in the European Union?

- [ ] Yes
- [ ] No

If the user selects `YES`, we display the `Vat Number` and `Country of Registrations `fields otherwise they stay hidden.

**Comment by chrisguindon** [comment]
@ZahraFazli,

Can you confirm that this is the text and behavior that we want here?

**Comment by ZahraFazli** [comment]
Looks good. Thanks!

**Comment by PaulWhite-Eclipse** [comment]
Just a nit.   “Country of Registrations” should be “Country of Registration” (with no “s”). Otherwise, looks good.

**Comment by chrisguindon** [comment]
This has been implemented.
