### ISSUE TITLE
Create cron tasks for removing stales form submissions

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#139]
As discussed on https://github.com/EclipseFdn/react-eclipsefdn-members/issues/19: 

- Completed forms can be held for 120 days.
- incomplete forms don't need to be kept for any longer than 60 days after their last mod

The number of days must be defined as configuration properties since we might want to change them in the future.

I am thinking that we can leverage Quarkus scheduler to define a job that runs once a day:

- https://quarkus.io/guides/scheduler
- https://quarkus.io/guides/quartz

**Comment by chrisguindon** [comment]
The deadline for this task is September 30 since we don't need to delete any forms within the first 2 months of launching the app.

**Comment by autumnfound** [comment]
This has been merged in so I'll be closing this issue
