### ISSUE TITLE
Implement user account quick links with picture

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#145]
This refers to this component:

![Screenshot 2021-06-28 135428](https://user-images.githubusercontent.com/893942/123681915-5f9ef600-d818-11eb-83a0-77f2acc349eb.png)

The links here should be the same as on any other eclipse.org website:

- View my account
- Edit my account
- Manage Cookies
- Logout

The picture is available from our API:
https://api.eclipse.org/account/profile/cguindon

https://api.eclipse.org/account/profile/:username

**Comment by linkfang** [comment]
Close this as the PR was merged
