### ISSUE TITLE
Create development documentation + guides

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#15]
To better enable community support in the future, steps to produce a development environment should be documented within the project. This applies to both the front end and back end, and both should be configurable to better enable diverse environments.

**Comment by chrisguindon** [comment]
The priority here is to document everything a developer needs to know in order to run this app (api+web) on his laptop to contribute to the project.

This should also include some information on how to use keycloak with this App.

**Comment by chrisguindon** [comment]
We've been actively working on this. What else do you think we need before we can close this issue?

**Comment by autumnfound** [comment]
I think the makefile I'm doing + adding the API to the stack will cover everything we need for this once its running. A few configuration steps + running a make command to prep for starting everything else up is pretty solid a start I think

**Comment by chrisguindon** [comment]
We are done!
