### ISSUE TITLE
Create FAQ Content

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#151]
This issue is to track the effort of creating the FAQ content which we will need for https://github.com/EclipseFdn/react-eclipsefdn-members/issues/150

**Comment by shanda-eclipse** [comment]
I will work with @ZahraFazli to create this content. We will most likely use this as our starting point: https://www.eclipse.org/membership/faq/#work-member

**Comment by chrisguindon** [comment]
@shanda-eclipse Is it reasonable for us to expect the content to be shared with us by October 31, 2021?

**Comment by shanda-eclipse** [comment]
@ZahraFazli Were you picturing an updated version of these FAQs? https://www.eclipse.org/membership/faq/

Really only the first section would be relevant to existing members logged into the portal. Either way that page will need to be updated.

**Comment by shanda-eclipse** [comment]
Document started but I haven't had much time to work on this yet: https://docs.google.com/document/d/1gzYJLRb6zrpmHkO28bUtLkXpwfbKLOVPuuYIj6_nJ_M/edit?usp=sharing

**Comment by shanda-eclipse** [comment]
FAQs are ready to be added to staging: https://docs.google.com/document/d/1gzYJLRb6zrpmHkO28bUtLkXpwfbKLOVPuuYIj6_nJ_M/edit?usp=sharing

**Comment by chrisguindon** [comment]
Thanks @shanda-eclipse

**Comment by shanda-eclipse** [comment]
For the second question, can you update the content to:

Member Representative or their delegate(s) may make edits to the information publicly displayed on your Eclipse Foundation membership page on your organization profile. If you believe you should have this authority but do not have access, please contact membership.coordination@eclipse-foundation.org.

And link "your organizational profile" to /portal/org-profile

**Comment by linkfang** [comment]
Changes have been merged into release-1.2!
