### ISSUE TITLE
Define Content of Lorem Ipisum

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#152]
With https://github.com/EclipseFdn/react-eclipsefdn-members/issues/146, we plan on adding a section with static content/links:

![Screenshot 2021-06-28 144203](https://user-images.githubusercontent.com/893942/123687517-04243680-d81f-11eb-8b64-9405f52d5529.png)

This issue was created to track the effort of defining the actual content.

**Comment by chrisguindon** [comment]
@shanda-eclipse we should aim at defining how we will use this section. Let's try to sort this out before the end of September if possible

**Comment by shanda-eclipse** [comment]
I recommend we include these links:

- [Member newsletter](https://www.eclipse.org/community/newsletter/)
- [Explore our Members](https://www.eclipse.org/membership/exploreMembership.php)
- [Contact us](https://www.eclipse.org/org/foundation/contact.php)

We do not need time stamps next to any of these links, as they are evergreen content

**Comment by chrisguindon** [comment]
@linkfang The ask here is simply to update the content with what was provided by Shanda!

**Comment by linkfang** [comment]
Hi @shanda-eclipse , @chrisguindon .
Please preview the changes here:
https://deploy-preview-336--eclipsefdn-react-members.netlify.app/portal/dashboard

**Comment by shanda-eclipse** [comment]
Looks good @linkfang

**Comment by linkfang** [comment]
Changes have been merged into release-1.1
