### ISSUE TITLE
Updates to the /working_groups resource

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#167]
This is the data that we need to capture and serve via /working_groups 

The challenge here is getting this content. Paul mentioned that @ZahraFazli can help us with this.

@ZahraFazli can you provide a list of all participation levels for each WG. 

I think we can manage to get everything else once we have this list of participation level per WG.

```
{
    "cloud-development-tools":{
        "document_id":"d96a8cabd0d04f29dfe6",
        "title":"Eclipse Cloud Development Tools",
"charter":"https://www.eclipse.org/org/workinggroups/eclipse_cloud_development_charter.php",
        "website":"https://ecdtools.eclipse.org/",
        "levels":[
            {
                "relation":"WGAPS",
                "description":"Participant Member"
            },
            {
                "relation":"WGAPS",
                "description":"Service Provider Member"
            }
        ]
    }
}
```

**Comment by ZahraFazli** [comment]
Hi Chris, 
Please find Working Groups and their levels below

Adoptium Working Group
Strategic Member
Enterprise Member
Participant Member
Committer Member
Guest Member

AsciiDoc Working Group
Partner Member
Guest Member

Eclipse Cloud Development Tools Working Group
Strategic Member
Participant Member
Guest Member

Eclipse IDE Working Group
Strategic Member
Supporter Member
Committer Member
Guest Member

Eclipse Edge Native Working Group
Strategic Member
Gold Member
Silver Member
Committer Member
Guest Member

Eclipse IoT Working Group
Strategic Member
Participant Member
Guest Member

Jakarta EE Working Group
Strategic Member
Enterprise Member
Participant Member
Guest Member

MicroProfile Working Group
Corporate Member
Guest Member

Eclipse OpenADx Working Group
Driver Member
Development Member
User Member
Guest Member

Eclipse OpenGenesis Working Group
Driver Member
Development Member
Guest Member

Eclipse OpenMDM Working Group
Driver Member
User Member
Application Member
Service Provider Member
Guest Member

Eclipse OpenMobility Working Group
Participant Member 
Committer Member

Eclipse OpenPASS Working Group
Driver Member
Service Member
User Member
Guest Member

OSGi Working Group
Strategic Member
Participant Member
Guest Member

Sparkplug Working Group
Strategic Member
Participant Member
Guest Member

Tangle EE Working Group
Strategic Member
Participant Member
Guest Member

There are some working groups who do not have a formal participation agreement and thus participation levels are not defined. These working groups are listed below

GEMOC Research Working Group
Science Working Group

Please let me know if there's anything else needed. 

Zahra

**Comment by chrisguindon** [comment]
@ZahraFazli Do we want to allow users to use the enrollment form to join a WG without any participation levels?

**Comment by ZahraFazli** [comment]
All active working groups have a participation level (listed above). We should not allow users to enroll in a working group without selecting a participation level as Membership team would need to go back and forth with members confirming their level.

**Comment by PaulWhite-Eclipse** [comment]
Chris, that's a good catch that those two charters predate the requirement for a level of participation.  For purposes of the enrollment form, let's set the one membership level to be "Participant" for both of those.

**Comment by ZahraFazli** [comment]
Are we talking about GMOC and Science WG? I can't see Chris's comment

**Comment by chrisguindon** [comment]
@ZahraFazli Yes, you can see what I did here: https://github.com/chrisguindon/react-eclipsefdn-members/blob/4db29dcd75ab6f43159b5f0917b9c40fa9f7c43b/src/main/resources/working_groups.json
