### ISSUE TITLE
Manage Cookies button in tool bar doesn't work

### ISSUE THREAD

**Issue by linkfang** [EclipseFdn/react-eclipsefdn-members#176]
The button should have brought up this:
![image](https://user-images.githubusercontent.com/43075439/124803054-9f579300-df26-11eb-841f-04690d9e3e62.png)

But currently does not work in React app.

**Comment by linkfang** [comment]
Hi @chrisguindon ,

I checked the code and I think the reason this does not work is that we don't have solstice in REM project. 
In this case, I assume we should write some code to make this part work rather than importing solstice, right?

**Comment by autumnfound** [comment]
We can add solstice assets as a dependency, but only build a subset of it rather than the whole thing as well! The file you want is https://github.com/EclipseFdn/solstice-assets/blob/master/js/solstice.cookieconsent.js and it is standalone vanilla JS, no bootstrap or jq in sight.

**Comment by linkfang** [comment]
Now it's solved!
