### ISSUE TITLE
Allow users to login via Keycloak

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#18]
- [ ] Create a first step page with sign in and register button
- [ ] if Signin, show what forms the user has, or allow the user to create a new form 
- [ ] After selecting form, store form ID

**Comment by flora8984461** [comment]
Actually, for this one, I have made it with fake user data. Waiting for real login data.

**Comment by chrisguindon** [comment]
Closing. Users can now login with keycloak.
