### ISSUE TITLE
Should we disable dates in the past for WG effective date

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#188]
Currently able to create new form and set date to the past. While its easy to reject these forms, we should probably look at not allowing people to use dates in the past.

@chrisguindon should we loop Shanda in as this is a business question?

![image](https://user-images.githubusercontent.com/23018241/125952910-7fe9caef-e6d3-482f-84b5-f0c3103ecc77.png)

**Comment by chrisguindon** [comment]
@autumnfound Great question!

I think this is more of a question for @ZahraFazli but let's also include @shanda-eclipse for visibility.

@ZahraFazli Would there ever be a need or use that where a user would want to set the effective date to a previous day?

**Comment by ZahraFazli** [comment]
Hi Chris, 
I don't see any reason why any member would like to select a date in the past. There has been one off cases but  I would say block off the user's ability to select past dates. If they would like to select a date in the past, they can reach out to Membership Coordination
Thanks

**Comment by chrisguindon** [comment]
@linkfang Can you make sure that it's not possible for user to pick a date in the past.
