### ISSUE TITLE
GDPR Requirements

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#19]
Let's use this bug track our requirements to comply with GDPR/CCPA. 

- Data retention: How long do we we want to keep draft submissions in our database?

**Comment by chrisguindon** [comment]
This app will capture the PII about various contact of an organization. At this moment, this includes:

- First and last name
- Job Title
- email address
- Organization address

I propose that we delete INCOMPLETE form submissions after 180 days (6 months) of being created.

I also think we can also delete COMPLETED form submissions 120 days after being completed.

@agafgfafa, @PaulWhite-Eclipse,

Do you think we need to keep this data longer?

**Comment by PaulWhite-Eclipse** [comment]
Completed forms can be held for 120 days. 
I think incomplete forms don't need to be kept for any longer than 60 days.  The intent for keeping incomplete forms is to allow someone to pause for a period of time before returning to complete it.  60 days would be more than sufficient for such purposes.

**Comment by chrisguindon** [comment]
Thanks @PaulWhite-Eclipse ! 

I created an issue for implementing a solution for this:
https://github.com/EclipseFdn/react-eclipsefdn-members/issues/139

We will make the expirations time configurable to allow us to change them in the future if needed. Closing this issue in favor of: https://github.com/EclipseFdn/react-eclipsefdn-members/issues/139

I will open additional GDRPR discussion if/when we start storing additional PII in future features of this app.
