### ISSUE TITLE
Testing: Phase 1 - Share your feedback!

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#191]
We are now ready to start **Testing: Phase 1** in order to capture feedback from stakeholders and staff.

The Eclipse Membership Enrollment form is available via this URL:
https://membership-staging.eclipse.org/application

Our goal with this project is to streamline the onboarding process of new members by allowing them to enter the information that we need via a web form. Our current process requires new members to download a pdf that must be printed, fill, scanned, and then returned to us via email.

Our membership coordination team will share a link to this form when once they are ready to become a member. It's expected that these users will have spoken to our membership team before going to this page.

**Known issues:**

- Emails are being sent by Martin Lowe but should be sent from membership.coordination@eclipse-foundation.org 
- The list of WG is incomplete
- It's currently possible to continue a form submission that was already submitted.
- It's impossible to join more than 10 WG

Please leave any feedback on this issue! The first testing period will end Wednesday, July 21, 2021.

## Expected timeline

- Testing phase 1: July 16-21, 2021
- Create a list of action items based off the feedback from testing phase 1: July 22-23
- Fix remaining issues and bugs: July 19-30
- Office shutdown: August 2-6
- Testing Phase 2: August 11-13
- Finalize remaining bugs: August 16-20
- Buffer for the unexpected: August 23-27
- Deploy to production on August 30

**Comment by ZahraFazli** [comment]
Hi Chris,
Everything looks good. I received the attached error when I clicked Submit. I did receive the email of acknowledgement from Martin though. 
![image](https://user-images.githubusercontent.com/50374570/125991403-179d8b00-59d4-42c3-a4dc-36d641e613e9.png)

**Comment by ZahraFazli** [comment]
Content of the email looks good. @shanda-eclipse please confirm

**Comment by perrieclipse** [comment]
Hi Chris, I tested looks fine, I did get the same message that Zahra did after submitting.

**Comment by perrieclipse** [comment]
Also I used a fake email so obviously I did not get an email confirmation, never thought I should use a valid one even though it said to : ) , so you should have a bounced notification somewhere, and if so would membership be notified if someone competed a form with an invalid email?

**Comment by chrisguindon** [comment]
@perrieclipse You should have received an email since we use the email from your account not the one that you share with us in the form.

**Comment by perrieclipse** [comment]
Hmm well I did not receive one as of yet.

**Comment by perrieclipse** [comment]
the fake email I used on the form was perri.winkle@eclipse.org. But yes you are correct I did log in with my eclipse account.

**Comment by perrieclipse** [comment]
Perhaps the reason I did not get an email is because i had the error code like Zahra did. I will try again.

**Comment by chrisguindon** [comment]
@ZahraFazli @shanda-eclipse,

Please use https://github.com/EclipseFdn/react-eclipsefdn-members/issues/90 to discuss any changes that you need us to do for the emails.

**Comment by chrisguindon** [comment]
I created a new issue to track the "An unexpected error has occurred" error that some of you are experiencing! 
https://github.com/EclipseFdn/react-eclipsefdn-members/issues/197

**Comment by eclipsewebmaster** [comment]
Is it appropriate that the Postal Code field is always labeled as such, even for United States, and other countries that label it differently?

Also, I seem to have lost my session during filling out the form, and interacting with the online chat a little bit:

![image](https://user-images.githubusercontent.com/4520186/126202306-1950f008-d397-4000-b96d-9d31aacac3e5.png)

**Comment by eclipsewebmaster** [comment]
I've noticed this form, as well as the current production form, reference Welcome, droy! instead of something more user friendly, such as my real name

![image](https://user-images.githubusercontent.com/4520186/126203687-54ad960f-e415-438a-80f4-21c1bc87b5f2.png)

**Comment by eclipsewebmaster** [comment]
The final confirmation page has some wording that could use work:

1 =========
Confirmation message on submission:
We thank you for completing the membership application.

Change "Confirmation message on submission:" to "Thank you!" or "Thank you for your application" ?  Or remove it, as the sentence that follows explains it.

2 =========
Our membership coordination team will send a ready to sign membership documents to the signing authority.

Change to : "Our membership coordination team will send ready-to-sign membership documents to the signing authority." (this is consistent with the wording that comes afterwards.

**Comment by ZahraFazli** [comment]
Hi Chris, 
Paul and I reviewed the application form and just a couple of things that popped up are listed below
1- In the organization section, Twitter Handle, Province or State, and Postal Code should not be mandatory. 
2- In the Membership Section, members need to explicitly state their revenue. Another table (similar to the one in the Membership Agreement) needs to be added for members to explicitly state their revenue
3-Joining a Working Group is optional. It is not required for companies to join a Working Group. In the Working Group section, add the first question "Are you joining a Working Group?" Yes, would trigger everything else on the page. No, would leave the page blank for users to click next

Chris, I am happy to jump on a call today to walk you through the comments above
thanks!

**Comment by ZahraFazli** [comment]
The summary email received by Membership Coordination would need the following details
1- Header should read "Eclipse Foundation AISBL Membership Application date submitted _______" This is in order for Membership team to download and save that report as a legal document in the foundation DB.
2- whether they need a PO or VAT
3- Membership fees

**Comment by SharonCorbett** [comment]
1.  Twitter handle is a required field.  Should they have the ability to not enter a twitter handle if they do not have one (many members are research universities, etc...)  One cannot even enter N/A...we could end up with bogus information if this is a required field...

2. Company Information:
Please change "Same as member rep." under Company Marketing Representative and Company Accounting Representative to Same as Member Representative in both cases.  

3. Unexpected error when my Country information would not stick in the drop down field (three tries)  - this followed me not entering a twitter handle...

4.  Membership Level - Please Indicate the class of membership for which you are applying.  Why is the "I" capitalized?

5.  The dollar amounts in the Membership Fees table is not centered under the member headings.

6.  Please realize each working group has different levels of participation which will need to be served back according to the information in the charter/wgpa.

7. Adding Working Groups - choose two the same - An Expected occured.

8.  Signing Authority - Please Indicate the individual who has the signing authority for the agreement.  Why is the "I" capitalized?

9.  Confirmation message on submission:

Our membership coordination team will send a ready to sign membership documents to the signing authority. If you have not received the ready-to-sign agreement within 2 business days, please contact membership.coordination@eclipse-foundation.org

I would change to:

Our Membership Coordination Team will send ready-to-sign membership agreement(s) to the designated signing authority.  If they have not received the ready-to-sign agreement(s) within two business days, please contact us via membership.coordination@eclipse-foundation.org.

Hope this helps.

**Comment by ZahraFazli** [comment]
Hi Chris, 
As Sharon submitted the Application Form as a user, in the summary email that I (Membership Coordination) received, it did not specify who is a Working Group Rep for which working group. Sharon, as a user, joined both IoT and AsciiDoc and the summary showed her name for both Working Group Reps however did not specify.
If an org is signing up for more than one working group, Membership team would need to know which rep belongs to which working group. 
Thanks!

**Comment by SharonCorbett** [comment]
The email I received back "Thank you for completing the member enrollment form", I'd suggest the following edit:

Thank you for completing the Eclipse Foundation's Member Enrollment Form.  

It looks like we spell enrolment with one l and two - we should be consistent (see main page description)

I'd also suggest we include a sentence in the confirmation email that says:  If you did not submit the Enrollment Form, please change your password and contact us immediately or something similar...

**Comment by autumnfound** [comment]
> Hi Chris,
> As Sharon submitted the Application Form as a user, in the summary email that I (Membership Coordination) received, it did not specify who is a Working Group Rep for which working group. Sharon, as a user, joined both IoT and AsciiDoc and the summary showed her name for both Working Group Reps however did not specify.
> If an org is signing up for more than one working group, Membership team would need to know which rep belongs to which working group.
> Thanks!

The way that this works, if different names had been specified on the form they should show differently to indicate. This seeming error only occurs when you use the same name repeatedly. I can add more unique information (like an ID), but it would clutter the section a little.

**Comment by chrisguindon** [comment]
Thanks to everyone who participated in this first testing phase. I created actions items to address all of these issues which you can all see listed here:
https://github.com/EclipseFdn/react-eclipsefdn-members/labels/feedback
