### ISSUE TITLE
Server responds 302 redirect when there is no token/q_session

### ISSUE THREAD

**Issue by linkfang** [EclipseFdn/react-eclipsefdn-members#193]
When we delete the q_session during an application, and then proceed to next page, we will receive a 302-redirect response from the server and then hit the CORS error.

![image](https://user-images.githubusercontent.com/43075439/126007377-80787428-4611-48e0-a120-fde4e07e1575.png)
![image](https://user-images.githubusercontent.com/43075439/126007384-f89d8102-ecb3-4f32-bb8c-a4607f7edadc.png)

We expect to receive a 401-unauthorized response so that React can bring users back to sign in page with a message reminding them the session has expired.

**Comment by chrisguindon** [comment]
I am marking this as a top priority. The API should not redirect the client to our auth server other than on the expected endpoint for that which is /api/login.
