### ISSUE TITLE
Eclipse Membership Portal

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#20]
The goal of this issue is to capture requirements for the next stage of this project.

The first stage of this project is the Membership Enrollment initiative and most of the work for that is scheduled-in for Q1-Q2.

The second stage,  the Eclipse Membership Portal is scheduled to be worked on in Q3-Q4.

@shanda-eclipse Let's use this bug to capture requirements for this new Portal. We will then breakdown these requirements into top-level issues as we did with issue #4.

We need to discuss with @waynebeaton in order to help determine what we can do with our current data and what we will need to build to achieve our objectives.

**Comment by chrisguindon** [comment]
We also need to define user roles and their level of access for this project.

For example, Company reps could have access to edit the description of their organization but not an employee of that org.

**Comment by waynebeaton** [comment]
@chrisguindon is already aware of everything that we can do with the Foundation DB data.

The Dashboard database contains information about Git Commits, including the identity of the author(s) of the commit. By cross referencing with Foundation DB data, we can determine who committers work for. 

So, we can, for example, for a company, list their active committers, list to which Eclipse open source projects their committers are contributing, list individual commits made by authors in their employ, etc. We collect commit dates so, given a definition of "recent", we can show recent activity.

Caveat: committer affiliation is determined based on data in the Foundation database. My understanding is that we have incomplete committer affiliation history captured. So the quality of queries involving that information are limited by the quality of that information. In concrete terms, our ability to correctly associate individual commits with a particular organization gets harder the further back we go in history.

**Comment by shanda-eclipse** [comment]
Christie started a design for the portal awhile ago: https://preview.uxpin.com/ed034ca4ebdda232bbea10cb7ed2dd12fd2dfb94#/pages/129664726
Pass: Eclip5e!

We will need to revisit this design once we've finalized the member enrollment form design. 

We also need to define the required functionality for each area.

**Comment by chrisguindon** [comment]
Thanks @shanda-eclipse and @waynebeaton 

This is great information that we can use to start plan this project!

**Comment by agafgfafa** [comment]
The portal requires a lot of building blocks and contains many components. Is there a breakdown of smaller tasks to reach the end goal?

**Comment by chrisguindon** [comment]
We broke down this  project into 4 projects:

1. Membership Portal https://github.com/EclipseFdn/react-eclipsefdn-members/projects/7
2. Membership Enrollment: Infrastructure https://github.com/EclipseFdn/react-eclipsefdn-members/projects/6
3. Membership Enrollment: REST API: https://github.com/EclipseFdn/react-eclipsefdn-members/projects/5
4. Membership Enrollment: Website:  https://github.com/EclipseFdn/react-eclipsefdn-members/projects/2

Given the size of this project, many of these things should be work on in parallel. For example, we need to finalize the API in order to finish the Membership Enrollment: Website.


There is also a full list of tasks, question or concerned that team has been creating since we started to work on this: https://github.com/EclipseFdn/react-eclipsefdn-members/issues

**Comment by chrisguindon** [comment]
> The portal requires a lot of building blocks and contains many components. Is there a breakdown of smaller tasks to reach the end goal?

I do agree here, we need to break down this project into smaller tasks before the dev team starts implementing this in Q3.

**Comment by chrisguindon** [comment]
> > The portal requires a lot of building blocks and contains many components. Is there a breakdown of smaller tasks to reach the end goal?
> 
> I do agree here, we need to break down this project into smaller tasks before the dev team starts implementing this in Q3.

@agafgfafa It just occurred to me, that is one of my MBO for this quarter:

[Chris] Finalize the Dashboard Requirements
Define missing API endpoint for the initial dashboard page
Q3 and Q4 objectives enumerated

**Comment by chrisguindon** [comment]
Closing this bug. It's too broad for it to be useful.
