### ISSUE TITLE
Capture organization revenue in a field in the membership section

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#210]
This was requested in #191 and can be easily done. I'm thinking of adding the field to the FormOrganization object to make sure it's well encapsulated. This will require another call to be added to the form to update this object.

@shanda-eclipse @ZahraFazli what kind of accuracy do we need to define here? Is there any preamble text we would want to include?

**Comment by shanda-eclipse** [comment]
@ZahraFazli do the working groups all have the same ranges for revenue as EF membership? https://www.eclipse.org/membership/#tab-fees. If so, I would recommend a drop-down with these predetermined ranges:

- > €250 million
- €100 million - €250 million
- €50 million - €100 million
- €10 million - €50 million
- < €10 million
- < €1 million and < 10 employees
- N/A (We are Govt, Govt agency, Research Organization, NGO, Academic Institution, Publishing Organization or User Group)

If the working group ranges differ, then we probably need it to be an open-ended question. But we will need to dictate currency. 

Suggested preamble: Membership fees are based on the organization's annual corporate revenue. To accurately determine your fees, please let us know your corporate revenue. 

@ZahraFazli WDYT?

**Comment by ZahraFazli** [comment]
@shanda-eclipse All working groups have different fees, based on their annual corporate revenue. We have working group fees still in USD while the Membership fees are in Euros. 
The fee chart is listed in the WGPA (similar to the Membership Agreement). 

I like the suggested preamble. I would add "let us know your corporate revenue from all the Affiliates" There have been cases we had to let orgs know that the fee is based on the revenue from all the affiliates and not just one department. 

Thanks

**Comment by shanda-eclipse** [comment]
> @shanda-eclipse All working groups have different fees, based on their annual corporate revenue. We have working group fees still in USD while the Membership fees are in Euros.
> The fee chart is listed in the WGPA (similar to the Membership Agreement).
Ok, so we would want it to be an open field. Should we ask them to provide it in euros or give them the option to specify which currency they are entering?

**Comment by autumnfound** [comment]
If we need to capture emp number, does that change based on different WGs? Or do we have a standard array for ranges? I'm pretty sure its the latter, and that we can add that along with the other field if needed

**Comment by ZahraFazli** [comment]
@shanda-eclipse It should be Euros for Membership fees. 
Only EclipseIDE is billed in Euros, all other working groups have fees in USD.
@autumnfound The ranges vary for Working Groups. 
I am happy to post the fee structure of different working groups but this bug is not suitable to post screenshots right from the WGPA. Would all the fee structures displayed along with their WGs in a doc format would be suitable for you?

**Comment by autumnfound** [comment]
Maybe for phase 1 we will capture free text, with reporting on those numbers but no automatic checking of the membership fees and printing into the final email. We need to update a few systems to add more automatic magic, and Chris is out until the 11th, and I'm out next week. Does that work?

**Comment by ZahraFazli** [comment]
Hi- just an update on the content. We should add "let us know your aggregated corporate revenue from all corporate affiliates. For more information, please see our Affiliates Membership Guidelines here :https://www.eclipse.org/org/documents/eclipse_affiliates_membership_guidelines.pdf"

> @shanda-eclipse All working groups have different fees, based on their annual corporate revenue. We have working group fees still in USD while the Membership fees are in Euros.
> The fee chart is listed in the WGPA (similar to the Membership Agreement).
> 
> I like the suggested preamble. I would add "let us know your corporate revenue from all the Affiliates" There have been cases we had to let orgs know that the fee is based on the revenue from all the affiliates and not just one department.
> 
> Thanks

**Comment by shanda-eclipse** [comment]
> Hi- just an update on the content. We should add "let us know your aggregated corporate revenue from all corporate affiliates. For more information, please see our Affiliates Membership Guidelines here :https://www.eclipse.org/org/documents/eclipse_affiliates_membership_guidelines.pdf"

Minor tweak: link "Affiliates Membership Guidelines" rather than adding the URL afterward (one of my little pet peeves)

**Comment by ZahraFazli** [comment]
+1

**Comment by autumnfound** [comment]
This change is live on staging, so I'm closing this issue.
