### ISSUE TITLE
Unexpected error when session is expired

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#213]
Users are presented are shown an "Unexpected error" page if they submit the form but the session is expired.

We need to do better in handling this use case. Users should be asked to re-login when the session is expired. This should be easier now with the changes that were implemented for https://github.com/EclipseFdn/react-eclipsefdn-members/pull/208

**Comment by linkfang** [comment]
With previous fixes, this issue does not exist anymore.

Now, when the session expires, the user will be brought back to sign in page with a pop-up message asking for logging in again. And it will disappear after 5 seconds.
![image](https://user-images.githubusercontent.com/43075439/127199721-ce50879a-c5d3-4deb-b0c1-5c86377ae0a0.png)

Please let me know if we would like to act in some other ways.
