### ISSUE TITLE
Joining a Working Group should be optional

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#215]
It is not required for companies to join a Working Group. In the Working Group section, add the first question "Are you joining a Working Group?" Yes, would trigger everything else on the page. No, would leave the page blank for users to click next.

**Comment by autumnfound** [comment]
This also needs backend changes as we enforce this in the API as well

**Comment by linkfang** [comment]
What should I use as request body when user deletes all the working groups he/she chooses to join?

task flow:

- The user chooses a working group to join in working group page and goes to next page.
- The user comes back to working group page to uncheck joining a working group (does not want to join any)

In step 1, React already sends a POST request to create the working group the user selects.
But then in step 2, we need to delete what we created in the db to make sure working group table is empty.

In this case, what should I send to back end to delete the working groups?
I can send anything as request body, so I think we can pick something work better with backend.

**Comment by autumnfound** [comment]
See the open api spec, there is an endpoint in there ;)

**Comment by linkfang** [comment]
> See the open api spec, there is an endpoint in there ;)

Cool! I completely forgot I had used the DELETE request before...

But now I would receive a 403 forbidden response when I try to make a DELETE request, like so:
![image](https://user-images.githubusercontent.com/43075439/127060118-ac1698ad-9b5e-4bf2-97d0-98bce1d4512b.png)

I checked in the db, the form id and wg id is correct. Any reason could cause a 403 response?

**Comment by autumnfound** [comment]
@shanda-eclipse we are adding a checkbox to the Working Groups page that will hide/show the Working Group section, asking "Are you joining a Working Group?". Would you want any preamble there saying something along the lines of you can join a wg later through x process?

**Comment by shanda-eclipse** [comment]
Existing members can join working groups, but I don't think it's a simple process and definitely not something handled through the enrollment form, so it might confuse this process if we suggest they can "add on" later. @ZahraFazli WDYT?

**Comment by ZahraFazli** [comment]
@shanda-eclipthse I agree! Let's keep it simple by just asking whether they are joining a WG or not. 
In case they wanna join a WG later on, they can reach out to Membership Coordination or Program Managers. More often, Program Managers are the ones talking to the existing members to join a WG.

**Comment by autumnfound** [comment]
Sounds good, thanks guys! I wanted to discuss it and see if it would be useful, but it sounds like we already have the simplest/best way :)
