### ISSUE TITLE
Date picker

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#23]
I like this library: bootstrap-datepicker
but might have an issue making it work with React: https://github.com/uxsolutions/bootstrap-datepicker/issues/2249

I'll look into this later. 

Another potential lib I might use is: https://github.com/arqex/react-datetime

The current one I'm using is also fine, but it seems not to support when clicking on year / month, it shows the picker for year / month, it does it if you only use year or year & month. Created an issue to track: https://github.com/Hacker0x01/react-datepicker/issues/2709

**Comment by chrisguindon** [comment]
@linkfang Do you have any recommendations for a Date picker?

**Comment by linkfang** [comment]
I think we can use the date picker component in Material-UI to keep things more consistent, unless it doesn't match our requirements/expectations, then we can consider using some other ones.
Its style looks a little different from current UI design. So, I am not sure if that would be an issue? I personally think it's fine.

https://material-ui.com/components/pickers/#date-time-pickers

It has 2 versions of date picker
Material-UI design one (dialog one):
![image](https://user-images.githubusercontent.com/43075439/117208846-9a118700-adc3-11eb-921c-2cb6663481e4.png)
![image](https://user-images.githubusercontent.com/43075439/117208851-9c73e100-adc3-11eb-81b8-0c33f07d037c.png)

Native date picker (supported by browsers, Google recommend the Material-UI one)
![image](https://user-images.githubusercontent.com/43075439/117208998-caf1bc00-adc3-11eb-84a2-6c829b0c289a.png)

Pros and cons for Material-UI design one:
https://material-ui.com/components/pickers/#material-ui-pickers
Pros:
1. Modern looking/design
2. Recommended by Google/Material-UI
3. Has a year picker when user clicks on the year.
Cons:
1. Doesn't have a month picker when user clicks on the month

Pros and cons for Native date picker: 
https://material-ui.com/components/pickers/#datepickers
Pros:
1. Has a year picker when user clicks on the year/month.
2. Has a month picker when user clicks on the month/month.
3. Align with current UI design more.
Cons:
1. A relatively less attractive design.

Side note:
An alternative option, if the 2 date pickers above doesn't match our expectiation, we could use date picker component in Ant Design, which has both year and month picker and also a decent design, lol.
https://ant.design/components/date-picker/#When-To-Use
![image](https://user-images.githubusercontent.com/43075439/117211919-a0a1fd80-adc7-11eb-90eb-c41abde9f85b.png)

**Comment by linkfang** [comment]
So, I think the Native Date Picker in Material-UI might be a better choice, as it has both year picker and month picker and the design is not too bad and it also aligns well with the overall design.

**Comment by chrisguindon** [comment]
> So, I think the Native Date Picker in Material-UI might be a better choice, as it has both year picker and month picker and the design is not too bad and it also aligns well with the overall design.

I think that make sense given that we are planing to use it for the Membership Portal project.

**Comment by linkfang** [comment]
Used date picker in Material-UI:
https://material-ui.com/components/pickers/#datepickers
