### ISSUE TITLE
Propose to use material-ui-dropzone for uploading

### ISSUE THREAD

**Issue by linkfang** [EclipseFdn/react-eclipsefdn-members#231]
Material-UI doesn't have a text field for uploading. 
When we set the text field type to "file", it just uses the native upload style and doesn't look very nice and consistent with Material-UI.
![image](https://user-images.githubusercontent.com/43075439/128399160-d21335b9-d645-4845-bbff-1a0cf1993f08.png)

Material-UI suggests people using material-ui-dropzone ([url](https://material-ui.com/discover-more/related-projects/#upload)) which has a modern UI and more user-friendly upload experience.
We can either have the upload area on the page or a button to trigger the upload dialog.
![image](https://user-images.githubusercontent.com/43075439/128399399-01194da1-58d0-4226-a214-51b650a093ce.png)
![image](https://user-images.githubusercontent.com/43075439/128399406-7c9d7b8f-3f34-44f8-af0a-43d2619e79bb.png)

**Comment by linkfang** [comment]
Related to [issue157](https://github.com/EclipseFdn/react-eclipsefdn-members/issues/157)

**Comment by autumnfound** [comment]
I believe there was some work done in the past by @ericpoirier and @chrisguindon to update the uploader on the mainsite, but those might rely on PHP for marshalling the file. Just want to make sure we don't already have a solution for this

**Comment by ericpoirier** [comment]
> I believe there was some work done in the past by @ericpoirier and @chrisguindon to update the uploader on the mainsite, but those might rely on PHP for marshalling the file. Just want to make sure we don't already have a solution for this

I don't believe we have anything for that.

**Comment by chrisguindon** [comment]
+1 drag and drop upload
