### ISSUE TITLE
Form should confirm acceptance of terms of service/application

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#237]
Hi Martin, 
Attached you will find section E of the Membership Application form. As discussed earlier, Membership team would like to save the contents of this form into the FoundationDB as Membership Application. For this purpose, user would need to acknowledge and agree to terms of section E. A checkbox with the following will suffice:
1- We will publicly support Eclipse Foundation and its purpose.
2- We will acknowledge our commitment in principle to comply with the Bylaws........
3- We will provide Eclipse Foundation with our logo......

Before they submit the form, users need to comply with these guidelines. We capture these in the Membership Application form as of today. 
Thanks,
Zahra
![Capture](https://user-images.githubusercontent.com/50374570/129058523-b309f18c-9316-45ae-8d7b-a9aa173e1667.PNG)

_Originally posted by @ZahraFazli in https://github.com/EclipseFdn/react-eclipsefdn-members/issues/90#issuecomment-896926789_

**Comment by chrisguindon** [comment]
we do not need to store that information in the database. We simply need to add 3 required checkboxes before the user can submit the form

**Comment by linkfang** [comment]
Hi @ZahraFazli ,
Can you please offer the PDF file or the text version of these 3 terms?
In this way, I don't need to type all the text.
Thanks!

**Comment by chrisguindon** [comment]
@linkfang That PDF should be on our website. You should be able to copy the text from there. I will get you a link shortly.

**Comment by linkfang** [comment]
Hi @ZahraFazli , do we need a preamble for the 3 checkboxes? Something like "You have to agree all 3 terms above to be able to submit the application" to give our users a better idea of this step.

![image](https://user-images.githubusercontent.com/43075439/129095006-5a455a42-c7c4-42c1-a517-4779fa14ad5c.png)

**Comment by chrisguindon** [comment]
@linkfang The PDF is here:
https://www.eclipse.org/membership/documents/membership-information-form.pdf

You can find many of our existing membership documents on this page:
https://www.eclipse.org/membership/#tab-membership
