### ISSUE TITLE
Add a field to record the type of organization. 

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/react-eclipsefdn-members#256]
We need to add a field to record the type of organization. 
This would be a mandatory drop down list and would appear before the Member Representative section. 
The options would include:
- For Profit Organization
- Non-Profit Open Source Organization / User Group
- Academic Organization
- Standards Organization
- Government Organization, Government Agency, or NGO
- Publishing/Media Organization
- Research Institute
- All others

This information would also be useful to have as part of the summary received by the Membership Coordination team. 

For reference, please see the screenshot attached. 
Thanks,
Zahra
![Capture](https://user-images.githubusercontent.com/50374570/130130895-b06c3004-54f4-4fd3-9693-75021f55728f.PNG)

**Comment by linkfang** [comment]
Hi @ZahraFazli , might it be better if I put this drop down after organization name field rather than right before Member Representative section? As it is something related to the org.
![image](https://user-images.githubusercontent.com/43075439/130260244-57b97402-5d2e-49e9-979f-6ab4fb36b1a6.png)

What do you think?

**Comment by ZahraFazli** [comment]
Hi @linkfang Yes, that looks good, thanks!

**Comment by linkfang** [comment]
Hi @ZahraFazli , just would like to confirm the type options. 

You included a type called "For Profit Organization" in the text, but in the screenshot you offered, there is no such type. I assume we should include this type in the drop-down menu?

**Comment by autumnfound** [comment]
I'm pretty sure that is covered by the "Others" option, as it doesn't fall under an exemption type.

**Comment by ZahraFazli** [comment]
@autumnfound I am pretty sure I responded to Zhou on the slack channel, but yes correct, it is covered under "All Others (for e.g. for-profit)" option. The screenshot suggests the same. 
Thanks

**Comment by autumnfound** [comment]
Sorry, I noticed this issue as it blocked something for me in checking the production instance, and didn't realize it had been addressed elsewhere! I noticed a little while after I posted and asked Zhou to look into it :) Ty!

**Comment by linkfang** [comment]
Now the changes are live on staging
