### ISSUE TITLE
Recording Membership Revenue, Employee Count and Currency Information

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/react-eclipsefdn-members#257]
The revenue and the employee count fields should be a drop down list of the following ranges:

REVENUE
- > 1 B
- 250M – 1 B
- 100M – 250M
- 50M – 100M
- 10M – 50M
- 1-10M
- < 1M

EMPLOYEE COUNT
- 1. 1-10
- 2. 10-100
- 3. 100-1000
- 4. 1000-10,000
- 5. > 10,000

The Currency column does not need to be a drop down menu where the user can switch between USD and Euros. We need to however display the currency used for business. Please display the currency as Euros and eliminate the drop down option
@PaulWhite-Eclipse

Thanks,
Zahra

**Comment by PaulWhite-Eclipse** [comment]
Please add the following text to the text asking for their revenues: 

Choose Not Applicable if your organization is: 
Govt, Govt agencies, Research Organizations, NGOs, etc.
Academic, Publishing Organizations, User Groups, etc.

Specifically, the choices for revenues should read: 

> €1 billion
€100 million - €250 million
€50 million - €100 million
€10 million - €50 million
€1 million < €10 million
< €1 million
Not Applicable

**Comment by linkfang** [comment]
Hi @autumnfound , for the EMPLOYEE COUNT, can you update the validation for it? I will get a 400 error with the new value.

I think for now it only accepts number (like, 100) or string number (like, "100"), but now the value will be a pure string which could not be converted to a number (like, "10 - 100").

Thanks!

**Comment by linkfang** [comment]
Now the changes are live on staging
