### ISSUE TITLE
Minor typos and formatting issues

### ISSUE THREAD

**Issue by shanda-eclipse** [EclipseFdn/react-eclipsefdn-members#258]
- [ ] Step 2 Purchasing Process: Field still asks "Require or not". @ZahraFazli can confirm, but I would think this is not required
- [ ] Step 3: "Please indicate the class of membership for which you are applying" needs a period at the end, but I think Paul was suggesting content changes here anyway
- [ ] Step 5:  Change "Please Indicate the individual who has the signing authority for the agreement" to "Please indicate the individual who has the signing authority for the agreement." (lower case i and a period)
- [ ] Step 6: Change "Please review your completed membership application form." to "Please review your completed Membership Application Form." (matching capitalization)
- [ ] Step 6 Company information: Organization name is missing the title above the field
- [ ] Step 6 Company information: "Twitter" should be capitalized
- [ ] Step 6 Address: "Province" should be capitalized
- [ ] Step 6 Working Group(s) to Join: "The Working Group Representative" working needs to be capitalized

**Comment by ZahraFazli** [comment]
Step 2: This part is required. Users need to explicitly state whether a PO is required or not
Step 3: Issue 259 covers all changes requested by Paul.
