### ISSUE TITLE
Content updates to confirmation step

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#274]
"Confirmation message on submission:" is a bit odd to me. I think the title should be something like: Thank you or something more friendly than "Confirmation message on submission:". 

![Screenshot 2021-08-24 133557](https://user-images.githubusercontent.com/893942/130664698-beef2c71-9bd0-4b5a-9329-315b893f0ddb.png)

Let's use this google doc to finalize the content:
https://docs.google.com/document/d/18jp9kYHWfnUxC7G4QBWNc_cmmz_2GitQO_Xo6f-TMBA/edit#

**Comment by PaulWhite-Eclipse** [comment]
Text has been updated in google doc, and is good to go.

**Comment by PaulWhite-Eclipse** [comment]
Good catch.  How about: "Thank you for completing the Eclipse Foundation membership application process."

**Comment by chrisguindon** [comment]
> Good catch. How about: "Thank you for completing the Eclipse Foundation membership application process."

+1 I think that's much better!

**Comment by chrisguindon** [comment]
@linkfang I made a PR for this: https://github.com/EclipseFdn/react-eclipsefdn-members/pull/310

**Comment by chrisguindon** [comment]
@PaulWhite-Eclipse Do you have any objections with replacing the period with an exclamation mark?
