### ISSUE TITLE
Propose to move "First Step" out of the step

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#29]
Since how I structure the stepper and form is my stepper is part of the form. If the user opens a new form and later decide to move back to continue on another existing form, my data state might get messed. And I feel it reasonable to separate the sign in since normally that's more on the user dashboard. While form steps are for form. 

I'm also trying to figure out other ways to fix it.  Maybe I can reset the form. 

I still think moving Sign In out of the form process is better. 

I am taking a note of this to see what changes I need to make.

**Comment by autumnfound** [comment]
Sign in could be moved to be separate from the form, but that seems to be a different issue than state if/when you change forms. In reality, you should clear out your state object and start from scratch when you load or create a form. Which of these issues is the issue you are discussing here?

**Comment by flora8984461** [comment]
> Sign in could be moved to be separate from the form, but that seems to be a different issue than state if/when you change forms. In reality, you should clear out your state object and start from scratch when you load or create a form. Which of these issues is the issue you are discussing here?

It is because Sign in is inside the steps, which causes my form state a little bit weird to handle. (Probably I need to find a better solution).

But if we decide to move the  Sign in out, my current structure is good to go. That's why I am asking.

**Comment by autumnfound** [comment]
Even if we move the sign in button and just assume someone is logged in at this point, how does that impact the issues with form switching? That is independent of the sign in, and was a different mechanism that was asked for.

**Comment by flora8984461** [comment]
> Even if we move the sign in button and just assume someone is logged in at this point, how does that impact the issues with form switching? That is independent of the sign in, and was a different mechanism that was asked for.

It's the whole first step I think should be moved out. The first step should be when you load the form, which is company Information, instead of selecting forms. 

Cuz from Step 1 - Step review, it's a whole form state.

**Comment by autumnfound** [comment]
> > Even if we move the sign in button and just assume someone is logged in at this point, how does that impact the issues with form switching? That is independent of the sign in, and was a different mechanism that was asked for.
> 
> It's the whole first step I think should be moved out, not just the sign in button. The first step should be when you load the form, which is company Information, instead of selecting forms.
> 
> Cuz from Step 1 to Step review, it's a whole form state.

I'm failing to see why loading the form should be extracted. It sounds like the solution here is to have a way of cleaning the state of the form when we perform certain actions.

**Comment by flora8984461** [comment]
> > > Even if we move the sign in button and just assume someone is logged in at this point, how does that impact the issues with form switching? That is independent of the sign in, and was a different mechanism that was asked for.
> > 
> > 
> > It's the whole first step I think should be moved out, not just the sign in button. The first step should be when you load the form, which is company Information, instead of selecting forms.
> > Cuz from Step 1 to Step review, it's a whole form state.
> 
> I'm failing to see why loading the form should be extracted. It sounds like the solution here is to have a way of cleaning the state of the form when we perform certain actions.

Make sense, Let me test something.
