### ISSUE TITLE
What happens when create a new form?

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#30]
I think if the user creates a new form when he hits the button, I should send a request to the server and generate a new formId, so that if he redirects back to the first sign-in page, the new form shows up (even he did not input anything there).  And if he creates a new form, and continue with the next steps, each step I have a form Id to retrieve data or send data. (if empty then it's empty).

Or do you think I need to wait for them to finish the first step, then I can send a request to create a new form id?

**Comment by flora8984461** [comment]
Send request to create form right after clicking "Create a new form"

**Comment by autumnfound** [comment]
I think that semantically for the logic, you've got the right idea here. We should hold off on posting to create a new form until the user has some useful information to write. This saves us from having to deal with a ton of empty objects from people creating forms and poking around without any real data.

**Comment by flora8984461** [comment]
Make sense.

The behaviours in creating a new form would be:

At the beginning when creating the new form, not sending any request to create a form.

Once the user inputs the first-step information and clicking on "next", I send:
- POST to create a form, got the form Id in the res body. 
- Once got the formId (For my frontend here, I need to set current form Id context), continue to POST all the entries for the Orgs, contacts.

**Comment by autumnfound** [comment]
For new entries, that looks right to me! Just make sure to use PUT if you need to update a change every time. While semantically the POST and PUT are the same in the backend, its best to use the proper verbiage in case we add checks and validation

**Comment by chrisguindon** [comment]
We should simply delete the form and bring back the user at the beggening [DELETE] /form/{id}
