### ISSUE TITLE
Signing Authority

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#31]
I got confused about Signing Authority. As the design shows: https://xd.adobe.com/view/583c3ff2-1fdc-43e4-ad8a-6dc730f5bb38-0d6f/screen/ff54485a-aec0-48cd-90ef-a08fa444edf7
While our server spec has signing authority data.

We don't need Signing Authority checkbox anymore. Then how do I decide if this user has signing Auth? By checking their user info is the same as Signing Authority info?

Or should we bring the Signing Authority checkbox back?  As discussed with Martin, he thinks it's better they don't need to repeat users' own info if they have Signing Authority.

**Comment by chrisguindon** [comment]
This was discussed with @shanda-eclipse.

The expectation is the following:

You can either chose to pick an existing contact as a company rep or create a new contact.

**Comment by chrisguindon** [comment]
We will keep it simple here. We will create a new contact entity for each contact. We won't allow users to pick an existing contact in version 1.

We can improve this at a later time.

**Comment by chrisguindon** [comment]
I think what we have already is good! Closing.
