### ISSUE TITLE
Organization and WG don't load properly on continue

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#328]
When filling out the form on production, I noticed that continuing from the previous form did not properly load the organization or WG fields. They still exist in the database, as the WG at least was in the email sent out in the end even though I didn't define an additional field.

**Comment by autumnfound** [comment]
On further investigation, this seems to have been a momentary issue and can't be reproduced.

**Comment by linkfang** [comment]
After a new prod build, when I chose "Continue Existing Application", the organization data did not show up on the page. And in network tab, the org data received is an empty array.
![image](https://user-images.githubusercontent.com/43075439/132760492-bacc4088-1c8e-40ef-b18b-9331bda16e3e.png)

Martin checked the db, there is no org data associated with the form ID 8aa8a63f7b981767017b9835a6400014, but there are contacts data related to it.
![image](https://user-images.githubusercontent.com/43075439/132760722-ac4b1038-f7eb-4bfe-9139-8490548193cc.png)

Not sure why the org data is missing while there is signing authority contact data.

**Comment by autumnfound** [comment]
Chris mentioned it could have something to do with the new field, so we can take a look in the morning. I've mitigated the risk on existing forms for external users at least.

**Comment by autumnfound** [comment]
On investigation, this is a backend issue in relation to the DB clearing scheduled action. I had not anticipated it clearing out null entries, so there will need to be some repairs done to our data for the currently submitted form. I can submit a patch that checks that it exists as well.

**Comment by chrisguindon** [comment]
We believe that this issue is fixed. Closing for now.
