### ISSUE TITLE
What happens if the user goes to step n, without clicking on "Next" and goes back to the previous step?

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#34]
Just think of one thing: if the user finished the current step, let's say step n, but clicks back to the previous steps  ( n-1, n-2, etc.), next time when coming back to the current step n, the data will be overwritten by the fetch since I fetch the data on each time the current page renders.  (I wish there was a way I can trace the render and how the user behaves, but for now, I don't think there is a solution for this).

Martin suggest: 
Call the API to save the data once the user finishes entering the inputs. (I think it's too often calling the APIs, and the user might click or input a lot of times, and then the data is immediately overridden, probably the user wants the data back without saving it? For example, I entered some inputs, but on the second thought, I don't wanna save it, I just close the page and next time login, with the hope that the form is having the old data)

I think another easy fix would be:
Just rename the button "Next" to be "Save and Continue". This makes some sense to the user that they need to click the button to save the data. I think I have seen similar usages in some other forms.

**Comment by chrisguindon** [comment]
I would expect us to save the state each time the user navigates to the next or previous step.
