### ISSUE TITLE
Unable to find foundationdb service in OKD cluster

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#349]
I've done updates to try and include the service route for the FoundationDB API so that we can make requests to it from REM. It is unable to see the endpoint from the server. The service is named `eclipsefdn-foundationdb-api`, and maps 80 to internal 8080. I've tried http://eclipsefdn-foundationdb-api and http://eclipsefdn-foundationdb-api:8080 as tests, and neither seem to work. Looking for help from releng folks to solve this @mbarbero @fredg02

**Comment by mbarbero** [comment]
There is no service named `eclipsefdn-foundationdb-api` in the namespace. Please double check that you created it properly.

**Comment by autumnfound** [comment]
There is currently a staging service live, that has the name eclipsefdn-foundationdb-api-staging. I thought it would use the service label and do routing to staging or production based on that but I was wrong. The connection has been fixed, thanks!
