### ISSUE TITLE
What happens when Marketing Rep or Accounting Rep is the same or not the same as Company Rep changes? 

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#35]
I need to sober my thought on it.

Let me take an example.

The user created a form with different Company Rep, Marketing Rep, and Accounting Rep info.

Next time when the user modifies this form, he marks Marketing Rep as the same as Company Rep. Do I send a DELETE request to delete the Marketing Rep?

Or I should send a PUT request to change the Marketing Rep Info with the name, job title, and email in Company Rep? (the type will still be the marketing and company respectively)

What I mainly wonder is do we keep the entry of the contact_markting, but changed the info, or totally delete this contact_markting entry? 

-----------------------------------------

Let's see another use case.

The user is creating a new form.

He marks the Marketing Rep as the same as Company Rep. Do I send a POST request to create only one Company Rep? 

Or do I send two POST requests to create a Company Rep and a Marketing Rep, with the same info but with different types?

Create 2 or create 1 entry?

**Comment by autumnfound** [comment]
We maintain each of the contact entities separately, so you should do the PUT call to push the data with a different entity type. Right now we just duplicate the data, though we could look in the future at adding the possibility of lists of contact types for a contact. It would still require a PUT, and actually, add a DELETE call if it has ever been saved, but it would make managing the data easier in the end I think.

@chrisguindon what do you think?

**Comment by flora8984461** [comment]
So according to:  `We maintain each of the contact entities separately, so you should do the PUT call to push the data with a different entity type.`

I just need to call three requests for each contact once hit "next" button.

**Comment by chrisguindon** [comment]
+1 for keeping this simple! Let's store each contact as separate entities.

**Comment by chrisguindon** [comment]
I will add details about this via https://github.com/EclipseFdn/react-eclipsefdn-members/issues/31
