### ISSUE TITLE
Improve the re-usability of the components

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#40]
This is inspired by https://github.com/EclipseFdn/react-eclipsefdn-members/pull/21#discussion_r577073689

```
          disabled={isSubmitting}
          // variant="contained"
          // color="primary"
          className="btn btn-primary float-right"
          className={`btn ${isLastStep() ? `btn-secondary` : `btn-primary `}`}
```

rather than hardcode the button, a way we could do this is provide an override. If set, it would always have a given class, otherwise it would fallback to this. I'm not sure if that works with your current setup though, as I don't know if you have separate button calls, or if the submit/next button is just a single button outside the frame that is being redrawn.

Its more that this is less usable outside the context of this exact form on this site. What if we need different configs for different site forms? What if button style means we need different classes on the button on a different site? There is no way to inject a different button class to be used in these instances. This is fine for this form, but its good to keep in mind when writing reusable code that we usually like the ability to fine tune stuff like this. Maybe make an issue to track this as an enhancement

**Comment by chrisguindon** [comment]
I think we will need to review the codebase to make things more reusable. We will create separate issues once @linkfang has taken some time to review the codebase and make some of his recommendations.
