### ISSUE TITLE
React Router issues

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#42]
For now, I removed the React-Router lib since the current app is small. 

While it occurs to me, if we are going to build membership dashboard, which will include a lot of different pages (Components) to mount or unmount, router lib will be needed to help with switching between pages.

How Router works:
reference:
https://medium.com/@marcellamaki/a-brief-overview-of-react-router-and-client-side-routing-70eb420e8cde
https://medium.com/the-andela-way/understanding-the-fundamentals-of-routing-in-react-b29f806b157e

The issue we might have:
This happened when Martin embeded server code with mine, putting react app into the /js folder in the server application.
When I want to switch pages, it triggers the server trying to see if that router existing, causes 404.

Even we don't embed it under the js/ folder in the server repo, we might still consider if the host/domain name is the same, when you hit /foo for React, will the server also capture it and trying to find it in the server instead of working for just React? 

Actually, Open-VSX React webpage can be a good similar use case to our portal in the future. 
https://github.com/EclipseFdn/open-vsx.org
Can refer to `additionalRoutes` in https://github.com/EclipseFdn/open-vsx.org/blob/master/website/src/page-settings.tsx

**Comment by autumnfound** [comment]
Looking into those articles, it looks like there is a solution for our exact use-case:

> The BrowserRouter is used for applications which have a dynamic server that knows how to handle any type of URL whereas the HashRouter is used for static websites with a server that only responds to requests for files that it knows about.

If we make use of the hash router, we should be able to retain all of the functionality of the router while removing the dynamic server requirement.

**Comment by flora8984461** [comment]
Yea, after reading that doc, it gives me this thought too. I'll have a try later. Thanks Martin!

**Comment by flora8984461** [comment]
How to use HashRouter:

https://paulgrajewski.medium.com/using-context-and-hashrouter-in-react-87afcefc5966

**Comment by chrisguindon** [comment]
+1 We have a solution for this.
