### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#45]
After reading some articles, and reading my code, I think probably for working groups dropdown's options, we can cache the first loaded data in redux / context or local storage (the options of working groups are not sensitive data, I think use localstorage is fine?).

Or any other way to cache it? useMemo? 🤔

References:
https://www.smashingmagazine.com/2020/07/custom-react-hook-fetch-cache-data/ 
https://stackoverflow.com/questions/49574285/how-to-cache-fetched-data-in-react-without-redux
https://betterprogramming.pub/why-you-should-be-separating-your-server-cache-from-your-ui-state-1585a9ae8336

**Comment by chrisguindon** [comment]
Querying the API should be fine here.
