### ISSUE TITLE
None existing member vs existing 

### ISSUE THREAD

**Issue by flora8984461** [EclipseFdn/react-eclipsefdn-members#46]
I'm not sure if the following is still a requirement.

```
Non Members who do not want to join a working group would be able to select the "I do not want to join a working group at this time" and jump directly to question 6
Essential for existing members to select a working group

```

According to https://docs.google.com/document/d/1E1THXZ-YhL_Rp5wMKD79O9Hb1ynQsrlqagnNJE3EPr8/edit# 

Question: 
How to define a member as an Existing Member or Non Member?  If this is still a requirement... 

They all need to have an account, probably the difference is whether they have already applied for a membership?

**Comment by autumnfound** [comment]
This is still a requirement yes. Membership is a state witihin our DB of active enrollment, and isn't tied to the user or previous engagment. There could multiple users within a company managing different aspects potentially, so you can't rely on the users previous data either. This will require a ping to FoundationDB to validate if a membership enrollment exists already, and will likely be phase 2 of this form.

**Comment by flora8984461** [comment]
I am going to leave this issue as an enhancement to add option "I do not want to join working groups". (Since I need to do some other stuff like validation, and Data handling with it)

**Comment by chrisguindon** [comment]
The API will know if a user is an Eclipse Member.
