### ISSUE TITLE
Keycloak as Open Source Identity and Access Management Service

### ISSUE THREAD

**Issue by chrisguindon** [EclipseFdn/react-eclipsefdn-members#5]
As described in https://docs.google.com/document/d/1DAdolxLQrOAUqFSsBge5StGLAtTcMMIt-vfzumlnatY/edit#heading=h.1wj3ctmandot, the best way to securely implement OAuth in a JavaScript app is to keep the token management outside of JavaScript entirely.

We are planning to use Quarkus for this application.

After some initial testing, we discovered that Drupal OAuth and Quarkus aren't really compatible and we believe that it would require some significant effort to make this work with our current stack.

With that said, I would like to officially recommend that we start moving forward with Keycloak. 

> Keycloak is an open source software product to allow single sign-on with Identity and Access Management aimed at modern applications and services.

https://www.keycloak.org/

I think the timing is right for this since Drupal 7 EOL is approaching and we need to decide if we migrate to Drupal 8/9 or if we move to something else. 

Our Drupal solution did serve us well for the last 5 years but looking at the future, it simply does not make sense to keep this in a Content Management System (CMS) especially given all the investment we did in the last year with leveraging Quarkus to build new REST APIs.

Please discuss!

**Comment by mbarbero** [comment]
I've setup a Keycloak instance on our internal infra and opened an infra (non public) ticket with instructions about how to connect to it.

**Comment by chrisguindon** [comment]
@mbarbero I posted some documentation on how we expect to use Keycloak for this APP:

**Comment by mbarbero** [comment]
A new keycloak instance has been deployed internally and credentials have been shared with @chrisguindon.

**Comment by chrisguindon** [comment]
We now have a functional instance of keycloak running for Rem! Thanks @mbarbero
