### ISSUE TITLE
Additions to the Membership Enrollment Form

### ISSUE THREAD

**Issue by ZahraFazli** [EclipseFdn/react-eclipsefdn-members#68]
Hello. 
We require two additional questions in the Membership Enrollment Form

This information is required from members who would have fees but for Associates. (non-paying), this is not required

1- Does your organization require a Purchase Order to facilitate payment of your membership dues
(Yes/No)? _________
Please indicate any other instructions or contact information that will better facilitate Eclipse
Foundation to bill your organization.
_____________________________________________________
_____________________________________________________

2- VAT Registration
If your organization is registered for VAT in the European Union, please provide the following:
VAT number: ________________________ Country of registration: __________________

Thank you,
Zahra

**Comment by shanda-eclipse** [comment]
Both questions should be added to stage 2, below the accounting representative.

H4: Purchasing Process
"Does your organization require a Purchase Order to facilitate payment of your membership dues?"
[Drop-down (required): Yes, No, Not Applicable]

H4: VAT Registration
"If your organization is registered for VAT in the European Union, please provide the following:"
"VAT number:" [Single line text box (optional)]    "Country of registration:" [Single line text box (optional)]

**Comment by chrisguindon** [comment]
Done!
