### ISSUE TITLE
Create base API for retrieving and storing form data

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#8]
To supply the form data, we require an endpoint that can both send and receive form data for a given user and form. We should enable multiple forms per user by having a unique form ID. To better enable partial filling of the form, we will need multiple endpoints for the different points of data being stored (basic form data, contacts, addresses). We should have an update and read operation for each of these data points, with the option in the future of deletion to perform cleanup in case a user has excessive forms and requests it.

Part of the solution for this issue should provide an OpenAPI spec to enable better support of the endpoint + web UI. This spec should cover all of the requests made in an end-to-end form filling session, including deletion requests (which while not currently in scope is useful in development at least).

**Comment by chrisguindon** [comment]
Initial OpenAPI spec was added to the project today via #16.

We should prioritize finishing the spec based off our review of the new mock ups from #4.

**Comment by chrisguindon** [comment]
Looks like we are done here!
