### ISSUE TITLE
UI browser auto-fill is inconsistent

### ISSUE THREAD

**Issue by autumnfound** [EclipseFdn/react-eclipsefdn-members#89]
When auto-filling the first section of the form, it seems that some of the field representation names are kept (COMPANY_NAME being the one I noticed the most). This causes some of the fields to autofill with bad values and causes more churn as the user has to review all fields to make sure the right data was input.

**Comment by linkfang** [comment]
Hi Martin, can you test on this [PR87](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/88) when you get a chance?
I didn't reproduce the issue in it, so this might be solved.

**Comment by autumnfound** [comment]
> Hi Martin, can you test on this [PR87](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/88) when you get a chance?
> I didn't reproduce the issue in it, so this might be solved.

I tried this with an empty form, both in my normal browser and incognito: 

![image](https://user-images.githubusercontent.com/23018241/120846737-9008b280-c540-11eb-9dbc-5c806732c2ac.png)

The following was one of the attributes of the first name field. Notice the COMPANY_NAME? That seems to be the culprit from what I can tell.
```
overall type: COMPANY_NAME
server type: NO_SERVER_DATA
heuristic type: COMPANY_NAME
label: First Name
parseable name: representative.company.firstName
section: representative.company.firstName_1-default
field signature: 2989688670
form signature: 14306464658987218532
form renderer id: 2
field renderer id: 43
```

**Comment by linkfang** [comment]
Problem fixed!
