### ISSUE TITLE
Improve useEffect usage - Tech debt

### ISSUE THREAD

**Issue by linkfang** [EclipseFdn/react-eclipsefdn-members#93]
**Intro for useEffect**
useEffect lets us perform side effects in function components, such as:

- Data fetching
- Setting up a subscription
- Manually changing the DOM in React components

By default, useEffect runs both after the first render and after every update. And if we give it an array as the 2nd argument, it will skip running if the state or props in the array does not change. If leave the array empty, it will only run once after the 1st render.

Refer the [official doc](https://reactjs.org/docs/hooks-effect.html) for more details.

**The issue we have**

- ESLint suggests us to add almost all the states, props and functions we use in an useEffect into its dependency array.
- We need to perform API call to get the form data and then we need to save it into formik, so we need to use formik.setFieldValue().

As a result of above 2 points. 

- If we leave the dependency as an empty one, ESLint will complain that "React Hook useEffect has a missing dependency: 'formik'. Either include it or remove the dependency array react-hooks/exhaustive-deps".
- If we remove the dependency array, it will run after 1st render and every update which is not good for performance.
- If we add "formik" into dependency array,  useEffect will be triggered 1-2 more times than we expect/want. And it could lead to an infinite loop without proper code/solution. 

Initially I used "// eslint-disable-next-line react-hooks/exhaustive-deps" comment to silent the warnings.
But there should be a better way to eliminate them.

**Solutions I found**

- Use "// eslint-disable-next-line react-hooks/exhaustive-deps" comment to diable the rule for a specific useEffect. (The last option, try to avoid)
- Declare the function we need inside useEffect. (If it will not be used anywhere else)
- Use useCallback to define the function we use in useEffect to prevent it from changing among component updates.
- Try to avoid using useEffect for user actions, such as click and type values in text box. Use onClick and onChange instead.
- Use useReducer Hook.
- Use a ref to hold mutable variable.

Some resources for now:
[What can I do if my effect dependencies change too often?](https://reactjs.org/docs/hooks-faq.html#what-can-i-do-if-my-effect-dependencies-change-too-often)
[React hook useeffect has a missing dependency](https://www.akashmittal.com/useeffect-missing-dependency/#:~:text=Eslint%20throws%20react%20hook%20useeffect%20has%20a%20missing,Eslint%20should%20improve%20it%20in%20their%20next%20versions.)
[useEffect missing dependency, need advice](https://dev.to/r3wt/useeffect-missing-dependency-need-advice-4d6b)
[How to fix missing dependency warning when using useEffect React Hook?](https://stackoverflow.com/questions/55840294/how-to-fix-missing-dependency-warning-when-using-useeffect-react-hook)

**Comment by linkfang** [comment]
With [PR107](https://github.com/EclipseFdn/react-eclipsefdn-members/pull/107), for now, I added all the dependencies suggested by ESLint and made below changes:

- In CompanyInformationContacts component, instead of using useEffect to handle the "same as company" checkbox related logic, I use onChange of the check box component and member rep inputs.
- In FormChooser component, I used useCallback to define a function I used in useEffect to prevent it from changing among component updates, so that it won't cause an infinite loop.
- In other steps components, add if statement and cleanup to avoid "can't perform a React state update on an unmounted component" error. Refer [here](https://github.com/facebook/react/issues/14369#issuecomment-468267798)

So far, the trade-off of adding all dependencies is that some useEffect would be triggered 1-2 more times than we want. But it seems that React doesn't treat this as an issue, refer [here](https://reactjs.org/docs/hooks-effect.html#tip-optimizing-performance-by-skipping-effects), in the Note part, the 2nd last paragraph, saying "Also, don’t forget that React defers running useEffect until after the browser has painted, so doing extra work is less of a problem."

**Comment by linkfang** [comment]
Update on June 18:
Overall, less API calls and less dependencies and if statement conditions in useEffect. Won't unnecessarily trigger useEffect.

- Removed furthestpage from the dependency array by changing the way to get the field id when user chooses "Start New Application".
Instead of getting the field id by doing a GET request, now the field id will be updated after a successful POST request.

- Removed formik from the dependency array by using destructuring to get only the setFieldValue method.

- Removed useEffect in SigningAuthority component, as the update/operation will be triggered when we get the data in CompanyInfo component.

**Comment by chrisguindon** [comment]
Done
