### ISSUE TITLE
Deploy to staging

### ISSUE THREAD

**Issue by mbarbero** [EclipseFdn/react-eclipsefdn-members#96]
- [x] Create DNS records for membership.eclipse.org and membership-staging.eclipse.org
  - [ ] Wait for propagation
- [x]  Create reverse proxy configuration in front LB (nginx)
  - [ ] Wait for deployement
- [x] Deploy src/main/k8s/staging.yml
- [ ] Change deployment logic of Jenkinsfile (production branch -> production, master branch -> staging)

**Comment by mbarbero** [comment]
> * [ ]  Change deployment logic of Jenkinsfile (production branch -> production, master branch -> staging)

@autumnfound, I pretty sure that's the deployment logic you would want. Would you mind having taking at stab at this one? I'll review your changes. Thanks!

cc @chrisguindon

**Comment by chrisguindon** [comment]
The APP is now on staging! Thanks @mbarbero for the support!
